version: '3.9'
services:
  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: khoidaoo
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
